### ISSUE TITLE
Wrong Locations in JS file

### ISSUE THREAD

**Issue by Haneesh000** [zero-to-mastery/Animation-Nation#1837]
Seems like someone added their art to the js file but there is an issue. The arts are:

1. Mr. A's Amimation (not misspelled) by Mr. AnkitR (@MrARawal)
2. Simple Mexican flag by Jnovak5 (@jnovak5)

Either it is that they did not create an art or that they did not give the proper URL in javascript file.
When we click on their artworks we get 404 Not Found error by Netlify.

![image](https://github.com/zero-to-mastery/Animation-Nation/assets/92240889/36bac664-7b30-429e-97a2-60454df33a10)
![image](https://github.com/zero-to-mastery/Animation-Nation/assets/92240889/4de3143e-cfe6-4e02-ace0-35091842d844)

**Comment by Haneesh000** [comment]
So @MrARawal's art location is https://animation-nation.netlify.app/art/MrA-animation/ which is wrongly specified as https://animation-nation.netlify.app/Art/Mr.A-Animation/index.html

And, @jnovak5's art location is https://animation-nation.netlify.app/art/jnovak5/ which is wrongly specified as https://animation-nation.netlify.app/Art/index.html

**Comment by sophiabrandt** [comment]
@Haneesh000 Thanks for letting us know. I will take a look at this
