### ISSUE TITLE
There is a need to resolve conflict each time a PR is raised. It can be optimized for sure using minimal code change.

### ISSUE THREAD

**Issue by hanisntsolo** [zero-to-mastery/Animation-Nation#1848]
There is a need to resolve conflict each time a PR is raised. It can be optimized for sure using minimal code change.

**Comment by sophiabrandt** [comment]
@hanisntsolo what is your suggestion? Please feel free to make a PR with the suggested changes.

**Comment by Himanshuch8055** [comment]
Yes, I also face this problem when I create PR. The include.js file shows has conflict you need to change it.

**Comment by hanisntsolo** [comment]
@sophiabrandt my suggestion is to collect the user info from their respective folders as payloads and populate the cards dynamically that way you'll never get into merge conflict. I am working on a solution will raise a PR soon.

**Comment by l-white** [comment]
I am closing this issue. ZTM Github maintainers will help with merge conflicts during Hacktoberfest. There are too many contributions happening in a short amount of time to prevent merge conflicts.
