### ISSUE TITLE
[FEAT] There is no favicon in website.

### ISSUE THREAD

**Issue by Himanshuch8055** [zero-to-mastery/Animation-Nation#1869]
**The website does not have any favicon.**

![Screenshot 2023-10-03 224753](https://github.com/zero-to-mastery/Animation-Nation/assets/94627200/75232753-1ee8-4251-85ed-90ea3331ed4a)

**Comment by avyuktsoni0731** [comment]
hi @Himanshuch8055 . I would love to work on this issue, can i please get this issue assigned to me?

Thanks : )

**Comment by Himanshuch8055** [comment]
PR has already been created. check #1870

**Comment by Himanshuch8055** [comment]
@Aryashre14 
The problem is already solved. Check PR #1870. The pull request has already been raised.
