### ISSUE TITLE
READMe enhancement with cool badge and more appropriate section

### ISSUE THREAD

**Issue by SusheelThapa** [zero-to-mastery/Animation-Nation#2052]
![image](https://github.com/zero-to-mastery/Animation-Nation/assets/83917129/95633398-11d3-45c4-b33c-d9eca80cfabe)

**Comment by Ayush-Vish** [comment]
@SusheelThapa  @achwell  Please assign me this issue under hacktoberfest

**Comment by SusheelThapa** [comment]
@LaurelineP Can you assign this to me

**Comment by l-white** [comment]
@Ayush-Vish @SusheelThapa We do not assign tasks for this repo. Submit a pull request with these changes if you wish.
