### ISSUE TITLE
Add Go To top Button 

### ISSUE THREAD

**Issue by Saikatssd** [zero-to-mastery/Animation-Nation#2079]
🐞 Problem:

There is currently no "go to top" button on the webpage, making it difficult for users to quickly navigate to the top of the page.

📋 Steps to Solve the Problem:

    I would like to add a "go to top" button for improved user navigation.

**Comment by Gauravtb2253** [comment]
I would like to work on this. Please assign me.

**Comment by Saikatssd** [comment]
I have created the  so assign me.  you guys look for another issues or features

**Comment by sophiabrandt** [comment]
@l-white can you make a decision on this?

**Comment by MattCSmith** [comment]
> 🐞 Problem:
> 
> There is currently no "go to top" button on the webpage, making it difficult for users to quickly navigate to the top of the page.
> 
> 📋 Steps to Solve the Problem:
> 
> ```
> I would like to add a "go to top" button for improved user navigation.
> ```

Nice idea, please proceed with this @Saikatssd
