### ISSUE TITLE
Link broken: https://zero-to-mastery.github.io/Animation-Nation

### ISSUE THREAD

**Issue by ahassang** [zero-to-mastery/Animation-Nation#442]
Project art not visble on click.
<img width="749" alt="Screen Shot 2020-04-24 at 3 34 16 PM" src="https://user-images.githubusercontent.com/61300903/80250093-1d40be80-8641-11ea-8c8c-3fa4248ac60d.png">

**Comment by TemidoRocha** [comment]
Hello, it is broken because someone left unfinished code on file include.js, 2516-2521.
quote
    {
      artName: "MexicanMustache",
      pageLink: "./Art/AnimatedMustache/index.html",
      imageLink: "./Art/AnimatedMustache/MexicanMustache.gif",
      author: 'Andrés Alonso Gálvez',
	githubLink: 'https://github.com/Dondesconton/',
unquote

**Comment by christinetrant** [comment]
Hi, I have created a pull request as someone had saved their style.css as the main stylesheet - once my pull request is approved it should be back to normal!

**Comment by sophiabrandt** [comment]
> Hi, I have created a pull request as someone had saved their style.css as the main stylesheet - once my pull request is approved it should be back to normal!

@christinetrant Hi Christine, can you reference your pull request here? I can't seem to find it.

**Comment by sophiabrandt** [comment]
I think issue was solved with @christinetrant 's PR.
There was an unrelated syntax error in `include.js`.
Fixed with https://github.com/zero-to-mastery/Animation-Nation/pull/648.
I will close this now.
