### ISSUE TITLE
index.html is empty

### ISSUE THREAD

**Issue by thiago-cs** [zero-to-mastery/Animation-Nation#842]
Hi guys! This _index.html_ in root is empty in its current version.

**Comment by majewski-piotr** [comment]
this is the commit that removed index.html

https://github.com/zero-to-mastery/Animation-Nation/commit/a1762acc18e42177732a1053a9012aa1a87b6f2d#diff-eacf331f0ffc35d4b482f1d15a887d3b

**Comment by MattCSmith** [comment]
This should be fixed now. 
Feel free though to fix any issues you come across 🙂
